import { Participante } from "../interfaces/participante";

export const PARTICIPANTES_DATA: Participante[] = [
  {
    id: "1",
    cedula: "0123456789",
    nombres: "Juan Carlos",
    apellidos: "Pérez López",
    sexo: "masculino",
    tipo: "atleta",
    fechaNacimiento: "1995-05-15",
    eventoId: 0,
  },
  {
    id: "2",
    cedula: "0987654321",
    nombres: "María José",
    apellidos: "González Ruiz",
    sexo: "femenino",
    tipo: "atleta",
    fechaNacimiento: "1998-08-22",
    eventoId: 0,
  },
  {
    id: "3",
    cedula: "0156789234",
    nombres: "Pedro Antonio",
    apellidos: "Martínez Silva",
    sexo: "masculino",
    tipo: "entrenador",
    fechaNacimiento: "1985-03-10",
    eventoId: 0,
  },
  {
    id: "4",
    cedula: "0198765432",
    nombres: "Ana Lucía",
    apellidos: "Fernández Castro",
    sexo: "femenino",
    tipo: "entrenador",
    fechaNacimiento: "1987-11-30",
    eventoId: 0,
  },
  {
    id: "5",
    cedula: "0134567890",
    nombres: "Carlos Alberto",
    apellidos: "Ramírez Mora",
    sexo: "masculino",
    tipo: "atleta",
    fechaNacimiento: "2000-01-18",
    eventoId: 0,
  },
  {
    id: "6",
    cedula: "0176543210",
    nombres: "Laura Patricia",
    apellidos: "Sánchez Vega",
    sexo: "femenino",
    tipo: "atleta",
    fechaNacimiento: "1996-07-25",
    eventoId: 0,
  },
  {
    id: "7",
    cedula: "0145678932",
    nombres: "Roberto Miguel",
    apellidos: "Torres Jiménez",
    sexo: "masculino",
    tipo: "entrenador",
    fechaNacimiento: "1982-09-12",
    eventoId: 0,
  },
  {
    id: "8",
    cedula: "0189765234",
    nombres: "Sofía Elena",
    apellidos: "Vargas Herrera",
    sexo: "femenino",
    tipo: "entrenador",
    fechaNacimiento: "1990-04-08",
    eventoId: 0,
  },
  {
    id: "9",
    cedula: "0167894523",
    nombres: "Diego Andrés",
    apellidos: "Morales Cruz",
    sexo: "masculino",
    tipo: "atleta",
    fechaNacimiento: "1999-11-20",
    eventoId: 0,
  },
  {
    id: "10",
    cedula: "0192837465",
    nombres: "Valentina Andrea",
    apellidos: "Rojas Mendoza",
    sexo: "femenino",
    tipo: "atleta",
    fechaNacimiento: "2001-06-14",
    eventoId: 0,
  },
  {
    id: "11",
    cedula: "0156473829",
    nombres: "Fernando José",
    apellidos: "Ortiz Salazar",
    sexo: "masculino",
    tipo: "atleta",
    fechaNacimiento: "1997-02-28",
    eventoId: 0,
  },
  {
    id: "12",
    cedula: "0183746529",
    nombres: "Carolina Isabel",
    apellidos: "Delgado Ponce",
    sexo: "femenino",
    tipo: "entrenador",
    fechaNacimiento: "1988-07-19",
    eventoId: 0,
  },
  {
    id: "13",
    cedula: "0174829364",
    nombres: "Alejandro Luis",
    apellidos: "Navarro Campos",
    sexo: "masculino",
    tipo: "entrenador",
    fechaNacimiento: "1984-12-03",
    eventoId: 0,
  },
  {
    id: "14",
    cedula: "0165738294",
    nombres: "Gabriela María",
    apellidos: "Ríos Gutiérrez",
    sexo: "femenino",
    tipo: "atleta",
    fechaNacimiento: "2000-03-25",
    eventoId: 0,
  },
  {
    id: "15",
    cedula: "0192847563",
    nombres: "Ricardo Javier",
    apellidos: "Flores Domínguez",
    sexo: "masculino",
    tipo: "atleta",
    fechaNacimiento: "1996-08-17",
    eventoId: 0,
  },
];
