export const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
  SECRETARIA: "SECRETARIA",
  CONTROL_PREVIO: "CONTROL_PREVIO",
  DTM_EIDE: "DTM_EIDE",
  DTM: "DTM",
  PDA: "PDA",
  FINANCIERO: "FINANCIERO",
  ENTRENADOR: "ENTRENADOR",
  METODOLOGO: "METODOLOGO",
  COMPRAS_PUBLICAS: "COMPRAS_PUBLICAS",
} as const;

export type Role = keyof typeof ROLES;
