export const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
  SECRETARIA: "SECRETARIA",
  DTM: "DTM",
  METODOLOGO: "METODOLOGO",
  ENTRENADOR: "ENTRENADOR",
  USUARIO: "USUARIO",
  DEPORTISTA: "DEPORTISTA",
  PDA: "PDA",
  CONTROL_PREVIO: "CONTROL_PREVIO",
  FINANCIERO: "FINANCIERO",
  COMPRAS_PUBLICAS: "COMPRAS_PUBLICAS",
} as const;

export type Role = (typeof ROLES)[keyof typeof ROLES];
