import { Aval } from "../interfaces/aval";

export const avales: Aval[] = [
  {
    id: "1",
    title: "Producto A",
    description: "Desc A",
    status: "sent",
    amount: 10,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    title: "Producto B",
    description: "Desc B",
    status: "approved",
    amount: 20,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3",
    title: "Producto C",
    description: "Desc C",
    status: "rejected",
    amount: 30,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "4",
    title: "Producto D",
    description: "Desc D",
    status: "pending",
    amount: 45,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "5",
    title: "Producto E",
    description: "Desc E",
    status: "approved",
    amount: 67,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "6",
    title: "Producto F",
    description: "Desc F",
    status: "rejected",
    amount: 89,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "7",
    title: "Producto G",
    description: "Desc G",
    status: "pending",
    amount: 123,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "8",
    title: "Producto H",
    description: "Desc H",
    status: "approved",
    amount: 156,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "9",
    title: "Producto I",
    description: "Desc I",
    status: "rejected",
    amount: 178,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "10",
    title: "Producto J",
    description: "Desc J",
    status: "pending",
    amount: 234,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "11",
    title: "Producto K",
    description: "Desc K",
    status: "approved",
    amount: 267,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "12",
    title: "Producto L",
    description: "Desc L",
    status: "rejected",
    amount: 289,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "13",
    title: "Producto M",
    description: "Desc M",
    status: "pending",
    amount: 345,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "14",
    title: "Producto N",
    description: "Desc N",
    status: "approved",
    amount: 378,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "15",
    title: "Producto O",
    description: "Desc O",
    status: "rejected",
    amount: 412,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "16",
    title: "Producto P",
    description: "Desc P",
    status: "pending",
    amount: 456,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "17",
    title: "Producto Q",
    description: "Desc Q",
    status: "approved",
    amount: 489,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "18",
    title: "Producto R",
    description: "Desc R",
    status: "rejected",
    amount: 523,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "19",
    title: "Producto S",
    description: "Desc S",
    status: "pending",
    amount: 567,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "20",
    title: "Producto T",
    description: "Desc T",
    status: "approved",
    amount: 601,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "21",
    title: "Producto U",
    description: "Desc U",
    status: "rejected",
    amount: 634,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "22",
    title: "Producto V",
    description: "Desc V",
    status: "pending",
    amount: 678,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "23",
    title: "Producto W",
    description: "Desc W",
    status: "approved",
    amount: 712,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "24",
    title: "Producto X",
    description: "Desc X",
    status: "rejected",
    amount: 745,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "25",
    title: "Producto Y",
    description: "Desc Y",
    status: "pending",
    amount: 789,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "26",
    title: "Producto Z",
    description: "Desc Z",
    status: "approved",
    amount: 823,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "27",
    title: "Producto AA",
    description: "Desc AA",
    status: "rejected",
    amount: 856,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "28",
    title: "Producto BB",
    description: "Desc BB",
    status: "pending",
    amount: 890,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "29",
    title: "Producto CC",
    description: "Desc CC",
    status: "approved",
    amount: 934,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "30",
    title: "Producto DD",
    description: "Desc DD",
    status: "rejected",
    amount: 967,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "31",
    title: "Producto EE",
    description: "Desc EE",
    status: "pending",
    amount: 1001,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "32",
    title: "Producto FF",
    description: "Desc FF",
    status: "approved",
    amount: 1045,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "33",
    title: "Producto GG",
    description: "Desc GG",
    status: "rejected",
    amount: 1078,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "34",
    title: "Producto HH",
    description: "Desc HH",
    status: "pending",
    amount: 1112,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "35",
    title: "Producto II",
    description: "Desc II",
    status: "approved",
    amount: 1156,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "36",
    title: "Producto JJ",
    description: "Desc JJ",
    status: "rejected",
    amount: 1189,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "37",
    title: "Producto KK",
    description: "Desc KK",
    status: "pending",
    amount: 1223,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "38",
    title: "Producto LL",
    description: "Desc LL",
    status: "approved",
    amount: 1267,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "39",
    title: "Producto MM",
    description: "Desc MM",
    status: "rejected",
    amount: 1301,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "40",
    title: "Producto NN",
    description: "Desc NN",
    status: "sent",
    amount: 1334,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
