import { Aval } from "../interfaces/aval";

// Datos de prueba - Avales basados en eventos reales
export const avales: Aval[] = [
  {
    id: "1",
    codigoItem: 530301,
    evento: "PARTICIPACIÓN EN EL CAMPEONATO NACIONAL OFICIAL SUB 16, AJEDREZ",
    tipoEvento: "CAMPEONATO",
    tipoParticipacion: "PARTICIPACION",
    deporte: "AJEDREZ",
    provincia: "PICHINCHA",
    alcance: "NACIONAL",
    fechaInicio: "2025-03-12",
    fechaFin: "2025-03-16",
    categoria: "15-24 AÑOS",
    status: "approved",
    deportistas: [
      {
        id: "d1",
        nombre: "Carlos",
        apellido: "Méndez",
        cedula: "1234567890",
        sexo: "M",
        fechaNacimiento: "2009-05-15",
        categoria: "15-24 AÑOS",
      },
      {
        id: "d2",
        nombre: "María",
        apellido: "González",
        cedula: "1234567891",
        sexo: "F",
        fechaNacimiento: "2010-08-20",
        categoria: "15-24 AÑOS",
      },
      {
        id: "d3",
        nombre: "Luis",
        apellido: "Rodríguez",
        cedula: "1234567892",
        sexo: "M",
        fechaNacimiento: "2009-12-10",
        categoria: "15-24 AÑOS",
      },
    ],
    numeroDeportistasHombres: 2,
    numeroDeportistasMujeres: 1,
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 0,
    documentoUrl: "/documentos/aval-530301.pdf",
    documentoNombre: "solicitud-ajedrez-pichincha.pdf",
    fechaSolicitud: new Date("2025-02-15"),
    fechaAprobacion: new Date("2025-02-20"),
    usuarioId: "user-1",
    usuarioNombre: "Juan Pérez",
  },
  {
    id: "2",
    codigoItem: 530235,
    evento: "PARTICIPACIÓN EN EL CAMPEONATO NACIONAL OFICIAL SUB 14, AJEDREZ",
    tipoEvento: "CAMPEONATO",
    tipoParticipacion: "PARTICIPACION",
    deporte: "AJEDREZ",
    provincia: "CHIMBORAZO",
    alcance: "NACIONAL",
    fechaInicio: "2025-04-16",
    fechaFin: "2025-04-20",
    categoria: "10-14 AÑOS",
    status: "sent",
    deportistas: [],
    numeroDeportistasHombres: 0,
    numeroDeportistasMujeres: 0,
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 0,
    documentoUrl: "/documentos/aval-530235.pdf",
    documentoNombre: "solicitud-ajedrez-chimborazo.pdf",
    fechaSolicitud: new Date("2025-03-10"),
    usuarioId: "user-1",
    usuarioNombre: "Juan Pérez",
  },
  {
    id: "3",
    codigoItem: 530303,
    evento: "JUEGOS DEPORTIVOS NACIONALES JUVENILES/AJEDREZ",
    tipoEvento: "JUEGO",
    tipoParticipacion: "PARTICIPACION",
    deporte: "AJEDREZ",
    provincia: "MANABI",
    alcance: "NACIONAL",
    fechaInicio: "2025-06-01",
    fechaFin: "2025-06-30",
    categoria: "15-24 AÑOS",
    status: "pending",
    deportistas: [
      {
        id: "d4",
        nombre: "Andrea",
        apellido: "Castro",
        cedula: "1234567893",
        sexo: "F",
        fechaNacimiento: "2008-03-25",
        categoria: "15-24 AÑOS",
      },
      {
        id: "d5",
        nombre: "Miguel",
        apellido: "Torres",
        cedula: "1234567894",
        sexo: "M",
        fechaNacimiento: "2007-11-30",
        categoria: "15-24 AÑOS",
      },
    ],
    numeroDeportistasHombres: 1,
    numeroDeportistasMujeres: 1,
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 0,
    documentoUrl: "/documentos/aval-530303.pdf",
    documentoNombre: "solicitud-juegos-manabi.pdf",
    fechaSolicitud: new Date("2025-04-01"),
    usuarioId: "user-1",
    usuarioNombre: "Juan Pérez",
  },
  {
    id: "4",
    codigoItem: 530301,
    evento: "JUEGOS DEPORTIVOS NACIONALES MENORES /AJEDREZ",
    tipoEvento: "JUEGO",
    tipoParticipacion: "PARTICIPACION",
    deporte: "AJEDREZ",
    provincia: "GUAYAQUIL",
    alcance: "NACIONAL",
    fechaInicio: "2025-10-01",
    fechaFin: "2025-10-30",
    categoria: "10-14 AÑOS",
    status: "rejected",
    deportistas: [],
    numeroDeportistasHombres: 0,
    numeroDeportistasMujeres: 0,
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 0,
    documentoUrl: "/documentos/aval-rejected.pdf",
    documentoNombre: "solicitud-juegos-guayaquil.pdf",
    fechaSolicitud: new Date("2025-08-15"),
    fechaRechazo: new Date("2025-08-20"),
    motivoRechazo: "Documentación incompleta",
    usuarioId: "user-1",
    usuarioNombre: "Juan Pérez",
  },
  {
    id: "5",
    codigoItem: 530252,
    evento: "PARTICIPACIÓN EN EL CAMPEONATO NACIONAL OFICIAL SUB 18/ AJEDREZ",
    tipoEvento: "CAMPEONATO",
    tipoParticipacion: "PARTICIPACION",
    deporte: "AJEDREZ",
    provincia: "CHIMBORAZO",
    alcance: "NACIONAL",
    fechaInicio: "2025-04-16",
    fechaFin: "2025-04-20",
    categoria: "15-24 AÑOS",
    status: "approved",
    deportistas: [
      {
        id: "d6",
        nombre: "Sofía",
        apellido: "Ramírez",
        cedula: "1234567895",
        sexo: "F",
        fechaNacimiento: "2007-06-15",
        categoria: "15-24 AÑOS",
      },
      {
        id: "d7",
        nombre: "Diego",
        apellido: "Morales",
        cedula: "1234567896",
        sexo: "M",
        fechaNacimiento: "2008-01-20",
        categoria: "15-24 AÑOS",
      },
      {
        id: "d8",
        nombre: "Elena",
        apellido: "Vargas",
        cedula: "1234567897",
        sexo: "F",
        fechaNacimiento: "2009-09-05",
        categoria: "15-24 AÑOS",
      },
    ],
    numeroDeportistasHombres: 1,
    numeroDeportistasMujeres: 2,
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 0,
    documentoUrl: "/documentos/aval-530252.pdf",
    documentoNombre: "solicitud-campeonato-sub18.pdf",
    fechaSolicitud: new Date("2025-03-01"),
    fechaAprobacion: new Date("2025-03-05"),
    usuarioId: "user-1",
    usuarioNombre: "Juan Pérez",
  },
  {
    id: "6",
    codigoItem: 530310,
    evento: "PARTICIPACIÓN EN EL CAMPEONATO NACIONAL OFICIAL SUB 12, AJEDREZ",
    tipoEvento: "CAMPEONATO",
    tipoParticipacion: "PARTICIPACION",
    deporte: "AJEDREZ",
    provincia: "LOJA",
    alcance: "NACIONAL",
    fechaInicio: "2025-05-10",
    fechaFin: "2025-05-14",
    categoria: "10-14 AÑOS",
    status: "approved",
    deportistas: [
      {
        id: "d9",
        nombre: "Valeria",
        apellido: "Herrera",
        cedula: "1234567898",
        sexo: "F",
        fechaNacimiento: "2011-02-18",
        categoria: "10-14 AÑOS",
      },
      {
        id: "d10",
        nombre: "Jorge",
        apellido: "Paredes",
        cedula: "1234567899",
        sexo: "M",
        fechaNacimiento: "2012-07-22",
        categoria: "10-14 AÑOS",
      },
    ],
    numeroDeportistasHombres: 1,
    numeroDeportistasMujeres: 1,
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 0,
    documentoUrl: "/documentos/aval-530310.pdf",
    documentoNombre: "solicitud-ajedrez-loja.pdf",
    fechaSolicitud: new Date("2025-04-01"),
    fechaAprobacion: new Date("2025-04-05"),
    usuarioId: "user-2",
    usuarioNombre: "Ana Gómez",
  },
  {
    id: "7",
    codigoItem: 530320,
    evento: "PARTICIPACIÓN EN EL CAMPEONATO NACIONAL OFICIAL SUB 20, AJEDREZ",
    tipoEvento: "CAMPEONATO",
    tipoParticipacion: "PARTICIPACION",
    deporte: "AJEDREZ",
    provincia: "AZUAY",
    alcance: "NACIONAL",
    fechaInicio: "2025-07-05",
    fechaFin: "2025-07-10",
    categoria: "15-24 AÑOS",
    status: "pending",
    deportistas: [
      {
        id: "d11",
        nombre: "Gabriel",
        apellido: "Mora",
        cedula: "1234567800",
        sexo: "M",
        fechaNacimiento: "2006-03-12",
        categoria: "15-24 AÑOS",
      },
    ],
    numeroDeportistasHombres: 1,
    numeroDeportistasMujeres: 0,
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 0,
    documentoUrl: "/documentos/aval-530320.pdf",
    documentoNombre: "solicitud-ajedrez-azuay.pdf",
    fechaSolicitud: new Date("2025-05-20"),
    usuarioId: "user-3",
    usuarioNombre: "Pedro Ruiz",
  },
  {
    id: "8",
    codigoItem: 530340,
    evento: "PARTICIPACIÓN EN EL CAMPEONATO NACIONAL OFICIAL SUB 10, AJEDREZ",
    tipoEvento: "CAMPEONATO",
    tipoParticipacion: "PARTICIPACION",
    deporte: "AJEDREZ",
    provincia: "EL ORO",
    alcance: "NACIONAL",
    fechaInicio: "2025-08-15",
    fechaFin: "2025-08-19",
    categoria: "10-14 AÑOS",
    status: "sent",
    deportistas: [],
    numeroDeportistasHombres: 0,
    numeroDeportistasMujeres: 0,
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 0,
    documentoUrl: "/documentos/aval-530340.pdf",
    documentoNombre: "solicitud-ajedrez-eloro.pdf",
    fechaSolicitud: new Date("2025-07-01"),
    usuarioId: "user-4",
    usuarioNombre: "Lucía Salazar",
  },
  {
    id: "9",
    codigoItem: 530350,
    evento: "JUEGOS DEPORTIVOS NACIONALES UNIVERSITARIOS/AJEDREZ",
    tipoEvento: "JUEGO",
    tipoParticipacion: "PARTICIPACION",
    deporte: "AJEDREZ",
    provincia: "TUNGURAHUA",
    alcance: "NACIONAL",
    fechaInicio: "2025-09-10",
    fechaFin: "2025-09-15",
    categoria: "15-24 AÑOS",
    status: "approved",
    deportistas: [
      {
        id: "d12",
        nombre: "Esteban",
        apellido: "Cedeño",
        cedula: "1234567801",
        sexo: "M",
        fechaNacimiento: "2005-10-10",
        categoria: "15-24 AÑOS",
      },
      {
        id: "d13",
        nombre: "Daniela",
        apellido: "Molina",
        cedula: "1234567802",
        sexo: "F",
        fechaNacimiento: "2006-12-01",
        categoria: "15-24 AÑOS",
      },
    ],
    numeroDeportistasHombres: 1,
    numeroDeportistasMujeres: 1,
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 0,
    documentoUrl: "/documentos/aval-530350.pdf",
    documentoNombre: "solicitud-juegos-universitarios.pdf",
    fechaSolicitud: new Date("2025-08-01"),
    fechaAprobacion: new Date("2025-08-05"),
    usuarioId: "user-5",
    usuarioNombre: "Carmen Vélez",
  },
  {
    id: "10",
    codigoItem: 530360,
    evento: "PARTICIPACIÓN EN EL CAMPEONATO NACIONAL OFICIAL FEMENINO, AJEDREZ",
    tipoEvento: "CAMPEONATO",
    tipoParticipacion: "PARTICIPACION",
    deporte: "AJEDREZ",
    provincia: "ESMERALDAS",
    alcance: "NACIONAL",
    fechaInicio: "2025-11-20",
    fechaFin: "2025-11-25",
    categoria: "15-24 AÑOS",
    status: "rejected",
    deportistas: [],
    numeroDeportistasHombres: 0,
    numeroDeportistasMujeres: 0,
    numeroEntrenadoresHombres: 0,
    numeroEntrenadoresMujeres: 1,
    documentoUrl: "/documentos/aval-530360.pdf",
    documentoNombre: "solicitud-ajedrez-femenino.pdf",
    fechaSolicitud: new Date("2025-10-10"),
    fechaRechazo: new Date("2025-10-15"),
    motivoRechazo: "No cumple requisitos de inscripción",
    usuarioId: "user-6",
    usuarioNombre: "Rosa Andrade",
  },
  {
    id: "11",
    codigoItem: 530370,
    evento: "PARTICIPACIÓN EN EL CAMPEONATO NACIONAL OFICIAL SUB 13, AJEDREZ",
    tipoEvento: "CAMPEONATO",
    tipoParticipacion: "PARTICIPACION",
    deporte: "AJEDREZ",
    provincia: "CARCHI",
    alcance: "NACIONAL",
    fechaInicio: "2025-12-01",
    fechaFin: "2025-12-05",
    categoria: "10-14 AÑOS",
    status: "approved",
    deportistas: [
      {
        id: "d14",
        nombre: "Paula",
        apellido: "López",
        cedula: "1234567803",
        sexo: "F",
        fechaNacimiento: "2012-03-10",
        categoria: "10-14 AÑOS",
      },
    ],
    numeroDeportistasHombres: 0,
    numeroDeportistasMujeres: 1,
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 0,
    documentoUrl: "/documentos/aval-530370.pdf",
    documentoNombre: "solicitud-ajedrez-carchi.pdf",
    fechaSolicitud: new Date("2025-11-01"),
    fechaAprobacion: new Date("2025-11-05"),
    usuarioId: "user-7",
    usuarioNombre: "Mario Cedeño",
  },
  {
    id: "12",
    codigoItem: 530380,
    evento: "PARTICIPACIÓN EN EL CAMPEONATO NACIONAL OFICIAL SUB 15, AJEDREZ",
    tipoEvento: "CAMPEONATO",
    tipoParticipacion: "PARTICIPACION",
    deporte: "AJEDREZ",
    provincia: "BOLIVAR",
    alcance: "NACIONAL",
    fechaInicio: "2025-12-10",
    fechaFin: "2025-12-15",
    categoria: "15-24 AÑOS",
    status: "pending",
    deportistas: [
      {
        id: "d15",
        nombre: "Andrea",
        apellido: "Pazmiño",
        cedula: "1234567804",
        sexo: "F",
        fechaNacimiento: "2010-09-14",
        categoria: "15-24 AÑOS",
      },
    ],
    numeroDeportistasHombres: 0,
    numeroDeportistasMujeres: 1,
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 0,
    documentoUrl: "/documentos/aval-530380.pdf",
    documentoNombre: "solicitud-ajedrez-bolivar.pdf",
    fechaSolicitud: new Date("2025-11-10"),
    usuarioId: "user-8",
    usuarioNombre: "Sonia Torres",
  },
  {
    id: "13",
    codigoItem: 530390,
    evento: "JUEGOS DEPORTIVOS NACIONALES UNIVERSITARIOS/AJEDREZ",
    tipoEvento: "JUEGO",
    tipoParticipacion: "PARTICIPACION",
    deporte: "AJEDREZ",
    provincia: "SUCUMBÍOS",
    alcance: "NACIONAL",
    fechaInicio: "2025-12-20",
    fechaFin: "2025-12-25",
    categoria: "15-24 AÑOS",
    status: "sent",
    deportistas: [],
    numeroDeportistasHombres: 0,
    numeroDeportistasMujeres: 0,
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 0,
    documentoUrl: "/documentos/aval-530390.pdf",
    documentoNombre: "solicitud-juegos-sucumbios.pdf",
    fechaSolicitud: new Date("2025-12-01"),
    usuarioId: "user-9",
    usuarioNombre: "Luis Paredes",
  },
  {
    id: "14",
    codigoItem: 530400,
    evento: "PARTICIPACIÓN EN EL CAMPEONATO NACIONAL OFICIAL SUB 17, AJEDREZ",
    tipoEvento: "CAMPEONATO",
    tipoParticipacion: "PARTICIPACION",
    deporte: "AJEDREZ",
    provincia: "NAPO",
    alcance: "NACIONAL",
    fechaInicio: "2026-01-10",
    fechaFin: "2026-01-15",
    categoria: "15-24 AÑOS",
    status: "approved",
    deportistas: [
      {
        id: "d16",
        nombre: "Javier",
        apellido: "Mora",
        cedula: "1234567805",
        sexo: "M",
        fechaNacimiento: "2009-04-12",
        categoria: "15-24 AÑOS",
      },
    ],
    numeroDeportistasHombres: 1,
    numeroDeportistasMujeres: 0,
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 0,
    documentoUrl: "/documentos/aval-530400.pdf",
    documentoNombre: "solicitud-ajedrez-napo.pdf",
    fechaSolicitud: new Date("2025-12-10"),
    fechaAprobacion: new Date("2025-12-15"),
    usuarioId: "user-10",
    usuarioNombre: "Patricia León",
  },
  {
    id: "15",
    codigoItem: 530410,
    evento: "PARTICIPACIÓN EN EL CAMPEONATO NACIONAL OFICIAL SUB 19, AJEDREZ",
    tipoEvento: "CAMPEONATO",
    tipoParticipacion: "PARTICIPACION",
    deporte: "AJEDREZ",
    provincia: "PASTAZA",
    alcance: "NACIONAL",
    fechaInicio: "2026-02-01",
    fechaFin: "2026-02-05",
    categoria: "15-24 AÑOS",
    status: "rejected",
    deportistas: [],
    numeroDeportistasHombres: 0,
    numeroDeportistasMujeres: 0,
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 0,
    documentoUrl: "/documentos/aval-530410.pdf",
    documentoNombre: "solicitud-ajedrez-pastaza.pdf",
    fechaSolicitud: new Date("2026-01-01"),
    fechaRechazo: new Date("2026-01-05"),
    motivoRechazo: "Falta de aval federativo",
    usuarioId: "user-11",
    usuarioNombre: "Ricardo Viteri",
  },
  {
    id: "16",
    codigoItem: 530420,
    evento: "JUEGOS DEPORTIVOS NACIONALES ESCOLARES/AJEDREZ",
    tipoEvento: "JUEGO",
    tipoParticipacion: "PARTICIPACION",
    deporte: "AJEDREZ",
    provincia: "ORELLANA",
    alcance: "NACIONAL",
    fechaInicio: "2026-03-10",
    fechaFin: "2026-03-15",
    categoria: "10-14 AÑOS",
    status: "approved",
    deportistas: [
      {
        id: "d17",
        nombre: "Martina",
        apellido: "García",
        cedula: "1234567806",
        sexo: "F",
        fechaNacimiento: "2012-07-21",
        categoria: "10-14 AÑOS",
      },
    ],
    numeroDeportistasHombres: 0,
    numeroDeportistasMujeres: 1,
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 0,
    documentoUrl: "/documentos/aval-530420.pdf",
    documentoNombre: "solicitud-juegos-orellana.pdf",
    fechaSolicitud: new Date("2026-02-10"),
    fechaAprobacion: new Date("2026-02-15"),
    usuarioId: "user-12",
    usuarioNombre: "Gabriela Salas",
  },
  {
    id: "17",
    codigoItem: 530430,
    evento: "PARTICIPACIÓN EN EL CAMPEONATO NACIONAL OFICIAL SUB 21, AJEDREZ",
    tipoEvento: "CAMPEONATO",
    tipoParticipacion: "PARTICIPACION",
    deporte: "AJEDREZ",
    provincia: "SANTO DOMINGO",
    alcance: "NACIONAL",
    fechaInicio: "2026-04-01",
    fechaFin: "2026-04-05",
    categoria: "15-24 AÑOS",
    status: "pending",
    deportistas: [
      {
        id: "d18",
        nombre: "Tomás",
        apellido: "Navarrete",
        cedula: "1234567807",
        sexo: "M",
        fechaNacimiento: "2007-10-30",
        categoria: "15-24 AÑOS",
      },
    ],
    numeroDeportistasHombres: 1,
    numeroDeportistasMujeres: 0,
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 0,
    documentoUrl: "/documentos/aval-530430.pdf",
    documentoNombre: "solicitud-ajedrez-santodomingo.pdf",
    fechaSolicitud: new Date("2026-03-01"),
    usuarioId: "user-13",
    usuarioNombre: "Esteban Lema",
  },
  {
    id: "18",
    codigoItem: 530440,
    evento: "PARTICIPACIÓN EN EL CAMPEONATO NACIONAL OFICIAL SUB 11, AJEDREZ",
    tipoEvento: "CAMPEONATO",
    tipoParticipacion: "PARTICIPACION",
    deporte: "AJEDREZ",
    provincia: "COTOPAXI",
    alcance: "NACIONAL",
    fechaInicio: "2026-05-10",
    fechaFin: "2026-05-14",
    categoria: "10-14 AÑOS",
    status: "sent",
    deportistas: [],
    numeroDeportistasHombres: 0,
    numeroDeportistasMujeres: 0,
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 0,
    documentoUrl: "/documentos/aval-530440.pdf",
    documentoNombre: "solicitud-ajedrez-cotopaxi.pdf",
    fechaSolicitud: new Date("2026-04-01"),
    usuarioId: "user-14",
    usuarioNombre: "Mónica Herrera",
  },
  {
    id: "19",
    codigoItem: 530450,
    evento: "JUEGOS DEPORTIVOS NACIONALES UNIVERSITARIOS/AJEDREZ",
    tipoEvento: "JUEGO",
    tipoParticipacion: "PARTICIPACION",
    deporte: "AJEDREZ",
    provincia: "IMBABURA",
    alcance: "NACIONAL",
    fechaInicio: "2026-06-01",
    fechaFin: "2026-06-05",
    categoria: "15-24 AÑOS",
    status: "approved",
    deportistas: [
      {
        id: "d19",
        nombre: "Lucas",
        apellido: "Vega",
        cedula: "1234567808",
        sexo: "M",
        fechaNacimiento: "2008-02-11",
        categoria: "15-24 AÑOS",
      },
      {
        id: "d20",
        nombre: "Camila",
        apellido: "Ríos",
        cedula: "1234567809",
        sexo: "F",
        fechaNacimiento: "2009-06-23",
        categoria: "15-24 AÑOS",
      },
    ],
    numeroDeportistasHombres: 1,
    numeroDeportistasMujeres: 1,
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 0,
    documentoUrl: "/documentos/aval-530450.pdf",
    documentoNombre: "solicitud-juegos-imbabura.pdf",
    fechaSolicitud: new Date("2026-05-01"),
    fechaAprobacion: new Date("2026-05-05"),
    usuarioId: "user-15",
    usuarioNombre: "Andrea Cobo",
  },
  {
    id: "20",
    codigoItem: 530460,
    evento: "PARTICIPACIÓN EN EL CAMPEONATO NACIONAL OFICIAL SUB 23, AJEDREZ",
    tipoEvento: "CAMPEONATO",
    tipoParticipacion: "PARTICIPACION",
    deporte: "AJEDREZ",
    provincia: "LOS RÍOS",
    alcance: "NACIONAL",
    fechaInicio: "2026-07-10",
    fechaFin: "2026-07-15",
    categoria: "15-24 AÑOS",
    status: "pending",
    deportistas: [
      {
        id: "d21",
        nombre: "Santiago",
        apellido: "Bravo",
        cedula: "1234567810",
        sexo: "M",
        fechaNacimiento: "2007-08-19",
        categoria: "15-24 AÑOS",
      },
    ],
    numeroDeportistasHombres: 1,
    numeroDeportistasMujeres: 0,
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 0,
    documentoUrl: "/documentos/aval-530460.pdf",
    documentoNombre: "solicitud-ajedrez-losrios.pdf",
    fechaSolicitud: new Date("2026-06-10"),
    usuarioId: "user-16",
    usuarioNombre: "Carlos Yánez",
  },
  {
    id: "21",
    codigoItem: 530470,
    evento: "PARTICIPACIÓN EN EL CAMPEONATO NACIONAL OFICIAL SUB 25, AJEDREZ",
    tipoEvento: "CAMPEONATO",
    tipoParticipacion: "PARTICIPACION",
    deporte: "AJEDREZ",
    provincia: "MORONA SANTIAGO",
    alcance: "NACIONAL",
    fechaInicio: "2026-08-01",
    fechaFin: "2026-08-05",
    categoria: "15-24 AÑOS",
    status: "approved",
    deportistas: [
      {
        id: "d22",
        nombre: "Natalia",
        apellido: "Pérez",
        cedula: "1234567811",
        sexo: "F",
        fechaNacimiento: "2006-05-17",
        categoria: "15-24 AÑOS",
      },
    ],
    numeroDeportistasHombres: 0,
    numeroDeportistasMujeres: 1,
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 0,
    documentoUrl: "/documentos/aval-530470.pdf",
    documentoNombre: "solicitud-ajedrez-morona.pdf",
    fechaSolicitud: new Date("2026-07-01"),
    fechaAprobacion: new Date("2026-07-05"),
    usuarioId: "user-17",
    usuarioNombre: "María Cárdenas",
  },
  {
    id: "22",
    codigoItem: 530480,
    evento: "JUEGOS DEPORTIVOS NACIONALES ESCOLARES/AJEDREZ",
    tipoEvento: "JUEGO",
    tipoParticipacion: "PARTICIPACION",
    deporte: "AJEDREZ",
    provincia: "ZAMORA CHINCHIPE",
    alcance: "NACIONAL",
    fechaInicio: "2026-09-10",
    fechaFin: "2026-09-15",
    categoria: "10-14 AÑOS",
    status: "sent",
    deportistas: [],
    numeroDeportistasHombres: 0,
    numeroDeportistasMujeres: 0,
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 0,
    documentoUrl: "/documentos/aval-530480.pdf",
    documentoNombre: "solicitud-juegos-zamora.pdf",
    fechaSolicitud: new Date("2026-08-01"),
    usuarioId: "user-18",
    usuarioNombre: "Jorge Salinas",
  },
  {
    id: "23",
    codigoItem: 530490,
    evento: "PARTICIPACIÓN EN EL CAMPEONATO NACIONAL OFICIAL SUB 27, AJEDREZ",
    tipoEvento: "CAMPEONATO",
    tipoParticipacion: "PARTICIPACION",
    deporte: "AJEDREZ",
    provincia: "GALÁPAGOS",
    alcance: "NACIONAL",
    fechaInicio: "2026-10-01",
    fechaFin: "2026-10-05",
    categoria: "15-24 AÑOS",
    status: "approved",
    deportistas: [
      {
        id: "d23",
        nombre: "Emilia",
        apellido: "Suárez",
        cedula: "1234567812",
        sexo: "F",
        fechaNacimiento: "2005-12-22",
        categoria: "15-24 AÑOS",
      },
    ],
    numeroDeportistasHombres: 0,
    numeroDeportistasMujeres: 1,
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 0,
    documentoUrl: "/documentos/aval-530490.pdf",
    documentoNombre: "solicitud-ajedrez-galapagos.pdf",
    fechaSolicitud: new Date("2026-09-01"),
    fechaAprobacion: new Date("2026-09-05"),
    usuarioId: "user-19",
    usuarioNombre: "Sofía Andrade",
  },
  {
    id: "24",
    codigoItem: 530500,
    evento: "PARTICIPACIÓN EN EL CAMPEONATO NACIONAL OFICIAL SUB 29, AJEDREZ",
    tipoEvento: "CAMPEONATO",
    tipoParticipacion: "PARTICIPACION",
    deporte: "AJEDREZ",
    provincia: "SANTA ELENA",
    alcance: "NACIONAL",
    fechaInicio: "2026-11-10",
    fechaFin: "2026-11-15",
    categoria: "15-24 AÑOS",
    status: "pending",
    deportistas: [
      {
        id: "d24",
        nombre: "David",
        apellido: "Cruz",
        cedula: "1234567813",
        sexo: "M",
        fechaNacimiento: "2004-11-11",
        categoria: "15-24 AÑOS",
      },
    ],
    numeroDeportistasHombres: 1,
    numeroDeportistasMujeres: 0,
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 0,
    documentoUrl: "/documentos/aval-530500.pdf",
    documentoNombre: "solicitud-ajedrez-santaelena.pdf",
    fechaSolicitud: new Date("2026-10-10"),
    usuarioId: "user-20",
    usuarioNombre: "Julio Zambrano",
  },
  {
    id: "25",
    codigoItem: 530510,
    evento: "JUEGOS DEPORTIVOS NACIONALES UNIVERSITARIOS/AJEDREZ",
    tipoEvento: "JUEGO",
    tipoParticipacion: "PARTICIPACION",
    deporte: "AJEDREZ",
    provincia: "GUAYAS",
    alcance: "NACIONAL",
    fechaInicio: "2026-12-01",
    fechaFin: "2026-12-05",
    categoria: "15-24 AÑOS",
    status: "approved",
    deportistas: [
      {
        id: "d25",
        nombre: "Isabel",
        apellido: "Mendoza",
        cedula: "1234567814",
        sexo: "F",
        fechaNacimiento: "2007-03-09",
        categoria: "15-24 AÑOS",
      },
    ],
    numeroDeportistasHombres: 0,
    numeroDeportistasMujeres: 1,
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 0,
    documentoUrl: "/documentos/aval-530510.pdf",
    documentoNombre: "solicitud-juegos-guayas.pdf",
    fechaSolicitud: new Date("2026-11-01"),
    fechaAprobacion: new Date("2026-11-05"),
    usuarioId: "user-21",
    usuarioNombre: "Verónica Cueva",
  },
  {
    id: "26",
    codigoItem: 530520,
    evento: "PARTICIPACIÓN EN EL CAMPEONATO NACIONAL OFICIAL SUB 31, AJEDREZ",
    tipoEvento: "CAMPEONATO",
    tipoParticipacion: "PARTICIPACION",
    deporte: "AJEDREZ",
    provincia: "MANABÍ",
    alcance: "NACIONAL",
    fechaInicio: "2027-01-10",
    fechaFin: "2027-01-15",
    categoria: "15-24 AÑOS",
    status: "sent",
    deportistas: [],
    numeroDeportistasHombres: 0,
    numeroDeportistasMujeres: 0,
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 0,
    documentoUrl: "/documentos/aval-530520.pdf",
    documentoNombre: "solicitud-ajedrez-manabi.pdf",
    fechaSolicitud: new Date("2026-12-01"),
    usuarioId: "user-22",
    usuarioNombre: "Patricio Vera",
  },
  {
    id: "27",
    codigoItem: 530530,
    evento: "PARTICIPACIÓN EN EL CAMPEONATO NACIONAL OFICIAL SUB 33, AJEDREZ",
    tipoEvento: "CAMPEONATO",
    tipoParticipacion: "PARTICIPACION",
    deporte: "AJEDREZ",
    provincia: "PICHINCHA",
    alcance: "NACIONAL",
    fechaInicio: "2027-02-01",
    fechaFin: "2027-02-05",
    categoria: "15-24 AÑOS",
    status: "approved",
    deportistas: [
      {
        id: "d26",
        nombre: "Renato",
        apellido: "Gómez",
        cedula: "1234567815",
        sexo: "M",
        fechaNacimiento: "2003-10-10",
        categoria: "15-24 AÑOS",
      },
    ],
    numeroDeportistasHombres: 1,
    numeroDeportistasMujeres: 0,
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 0,
    documentoUrl: "/documentos/aval-530530.pdf",
    documentoNombre: "solicitud-ajedrez-pichincha.pdf",
    fechaSolicitud: new Date("2027-01-01"),
    fechaAprobacion: new Date("2027-01-05"),
    usuarioId: "user-23",
    usuarioNombre: "Sandra Molina",
  },
  {
    id: "28",
    codigoItem: 530540,
    evento: "JUEGOS DEPORTIVOS NACIONALES ESCOLARES/AJEDREZ",
    tipoEvento: "JUEGO",
    tipoParticipacion: "PARTICIPACION",
    deporte: "AJEDREZ",
    provincia: "AZUAY",
    alcance: "NACIONAL",
    fechaInicio: "2027-03-10",
    fechaFin: "2027-03-15",
    categoria: "10-14 AÑOS",
    status: "pending",
    deportistas: [
      {
        id: "d27",
        nombre: "Valentina",
        apellido: "Crespo",
        cedula: "1234567816",
        sexo: "F",
        fechaNacimiento: "2013-04-12",
        categoria: "10-14 AÑOS",
      },
    ],
    numeroDeportistasHombres: 0,
    numeroDeportistasMujeres: 1,
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 0,
    documentoUrl: "/documentos/aval-530540.pdf",
    documentoNombre: "solicitud-juegos-azuay.pdf",
    fechaSolicitud: new Date("2027-02-10"),
    usuarioId: "user-24",
    usuarioNombre: "Marcos Andrade",
  },
  {
    id: "29",
    codigoItem: 530550,
    evento: "PARTICIPACIÓN EN EL CAMPEONATO NACIONAL OFICIAL SUB 35, AJEDREZ",
    tipoEvento: "CAMPEONATO",
    tipoParticipacion: "PARTICIPACION",
    deporte: "AJEDREZ",
    provincia: "EL ORO",
    alcance: "NACIONAL",
    fechaInicio: "2027-04-01",
    fechaFin: "2027-04-05",
    categoria: "15-24 AÑOS",
    status: "approved",
    deportistas: [
      {
        id: "d28",
        nombre: "Joaquín",
        apellido: "Mena",
        cedula: "1234567817",
        sexo: "M",
        fechaNacimiento: "2002-09-09",
        categoria: "15-24 AÑOS",
      },
    ],
    numeroDeportistasHombres: 1,
    numeroDeportistasMujeres: 0,
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 0,
    documentoUrl: "/documentos/aval-530550.pdf",
    documentoNombre: "solicitud-ajedrez-eloro.pdf",
    fechaSolicitud: new Date("2027-03-01"),
    fechaAprobacion: new Date("2027-03-05"),
    usuarioId: "user-25",
    usuarioNombre: "Lorena Paredes",
  },
  {
    id: "30",
    codigoItem: 530560,
    evento: "PARTICIPACIÓN EN EL CAMPEONATO NACIONAL OFICIAL SUB 37, AJEDREZ",
    tipoEvento: "CAMPEONATO",
    tipoParticipacion: "PARTICIPACION",
    deporte: "AJEDREZ",
    provincia: "TUNGURAHUA",
    alcance: "NACIONAL",
    fechaInicio: "2027-05-10",
    fechaFin: "2027-05-14",
    categoria: "15-24 AÑOS",
    status: "rejected",
    deportistas: [],
    numeroDeportistasHombres: 0,
    numeroDeportistasMujeres: 0,
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 0,
    documentoUrl: "/documentos/aval-530560.pdf",
    documentoNombre: "solicitud-ajedrez-tungurahua.pdf",
    fechaSolicitud: new Date("2027-04-01"),
    fechaRechazo: new Date("2027-04-05"),
    motivoRechazo: "No cumple con la edad mínima",
    usuarioId: "user-26",
    usuarioNombre: "Cristina Vaca",
  },
  {
    id: "31",
    codigoItem: 530570,
    evento: "JUEGOS DEPORTIVOS NACIONALES UNIVERSITARIOS/AJEDREZ",
    tipoEvento: "JUEGO",
    tipoParticipacion: "PARTICIPACION",
    deporte: "AJEDREZ",
    provincia: "ESMERALDAS",
    alcance: "NACIONAL",
    fechaInicio: "2027-06-01",
    fechaFin: "2027-06-05",
    categoria: "15-24 AÑOS",
    status: "approved",
    deportistas: [
      {
        id: "d29",
        nombre: "Martín",
        apellido: "Quintero",
        cedula: "1234567818",
        sexo: "M",
        fechaNacimiento: "2001-07-07",
        categoria: "15-24 AÑOS",
      },
    ],
    numeroDeportistasHombres: 1,
    numeroDeportistasMujeres: 0,
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 0,
    documentoUrl: "/documentos/aval-530570.pdf",
    documentoNombre: "solicitud-juegos-esmeraldas.pdf",
    fechaSolicitud: new Date("2027-05-01"),
    fechaAprobacion: new Date("2027-05-05"),
    usuarioId: "user-27",
    usuarioNombre: "Javier Cedeño",
  },
  {
    id: "32",
    codigoItem: 530580,
    evento: "PARTICIPACIÓN EN EL CAMPEONATO NACIONAL OFICIAL SUB 39, AJEDREZ",
    tipoEvento: "CAMPEONATO",
    tipoParticipacion: "PARTICIPACION",
    deporte: "AJEDREZ",
    provincia: "LOJA",
    alcance: "NACIONAL",
    fechaInicio: "2027-07-10",
    fechaFin: "2027-07-15",
    categoria: "15-24 AÑOS",
    status: "pending",
    deportistas: [
      {
        id: "d30",
        nombre: "Daniela",
        apellido: "Paz",
        cedula: "1234567819",
        sexo: "F",
        fechaNacimiento: "2000-08-08",
        categoria: "15-24 AÑOS",
      },
    ],
    numeroDeportistasHombres: 0,
    numeroDeportistasMujeres: 1,
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 0,
    documentoUrl: "/documentos/aval-530580.pdf",
    documentoNombre: "solicitud-ajedrez-loja.pdf",
    fechaSolicitud: new Date("2027-06-10"),
    usuarioId: "user-28",
    usuarioNombre: "María Zamora",
  },
  {
    id: "33",
    codigoItem: 530590,
    evento: "PARTICIPACIÓN EN EL CAMPEONATO NACIONAL OFICIAL SUB 41, AJEDREZ",
    tipoEvento: "CAMPEONATO",
    tipoParticipacion: "PARTICIPACION",
    deporte: "AJEDREZ",
    provincia: "CARCHI",
    alcance: "NACIONAL",
    fechaInicio: "2027-08-10",
    fechaFin: "2027-08-15",
    categoria: "15-24 AÑOS",
    status: "approved",
    deportistas: [
      {
        id: "d31",
        nombre: "Marcos",
        apellido: "Paredes",
        cedula: "1234567820",
        sexo: "M",
        fechaNacimiento: "2002-03-15",
        categoria: "15-24 AÑOS",
      },
      {
        id: "d32",
        nombre: "Lucía",
        apellido: "García",
        cedula: "1234567821",
        sexo: "F",
        fechaNacimiento: "2003-11-22",
        categoria: "15-24 AÑOS",
      },
    ],
    numeroDeportistasHombres: 1,
    numeroDeportistasMujeres: 1,
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 0,
    documentoUrl: "/documentos/aval-530590.pdf",
    documentoNombre: "solicitud-ajedrez-carchi41.pdf",
    fechaSolicitud: new Date("2027-07-01"),
    fechaAprobacion: new Date("2027-07-05"),
    usuarioId: "user-29",
    usuarioNombre: "Andrea López",
  },
  {
    id: "34",
    codigoItem: 530600,
    evento: "JUEGOS DEPORTIVOS NACIONALES ESCOLARES/AJEDREZ",
    tipoEvento: "JUEGO",
    tipoParticipacion: "PARTICIPACION",
    deporte: "AJEDREZ",
    provincia: "BOLIVAR",
    alcance: "NACIONAL",
    fechaInicio: "2027-09-10",
    fechaFin: "2027-09-15",
    categoria: "10-14 AÑOS",
    status: "sent",
    deportistas: [],
    numeroDeportistasHombres: 0,
    numeroDeportistasMujeres: 0,
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 0,
    documentoUrl: "/documentos/aval-530600.pdf",
    documentoNombre: "solicitud-juegos-bolivar.pdf",
    fechaSolicitud: new Date("2027-08-01"),
    usuarioId: "user-30",
    usuarioNombre: "Carlos Medina",
  },
  {
    id: "35",
    codigoItem: 530610,
    evento: "PARTICIPACIÓN EN EL CAMPEONATO NACIONAL OFICIAL SUB 43, AJEDREZ",
    tipoEvento: "CAMPEONATO",
    tipoParticipacion: "PARTICIPACION",
    deporte: "AJEDREZ",
    provincia: "GUAYAS",
    alcance: "NACIONAL",
    fechaInicio: "2027-10-05",
    fechaFin: "2027-10-10",
    categoria: "15-24 AÑOS",
    status: "pending",
    deportistas: [
      {
        id: "d33",
        nombre: "Santiago",
        apellido: "Mora",
        cedula: "1234567822",
        sexo: "M",
        fechaNacimiento: "2004-06-18",
        categoria: "15-24 AÑOS",
      },
    ],
    numeroDeportistasHombres: 1,
    numeroDeportistasMujeres: 0,
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 0,
    documentoUrl: "/documentos/aval-530610.pdf",
    documentoNombre: "solicitud-ajedrez-guayas43.pdf",
    fechaSolicitud: new Date("2027-09-01"),
    usuarioId: "user-31",
    usuarioNombre: "María Torres",
  },
  {
    id: "36",
    codigoItem: 530620,
    evento: "JUEGOS DEPORTIVOS NACIONALES UNIVERSITARIOS/AJEDREZ",
    tipoEvento: "JUEGO",
    tipoParticipacion: "PARTICIPACION",
    deporte: "AJEDREZ",
    provincia: "SUCUMBÍOS",
    alcance: "NACIONAL",
    fechaInicio: "2027-11-15",
    fechaFin: "2027-11-20",
    categoria: "15-24 AÑOS",
    status: "rejected",
    deportistas: [],
    numeroDeportistasHombres: 0,
    numeroDeportistasMujeres: 0,
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 0,
    documentoUrl: "/documentos/aval-530620.pdf",
    documentoNombre: "solicitud-juegos-sucumbios.pdf",
    fechaSolicitud: new Date("2027-10-10"),
    fechaRechazo: new Date("2027-10-15"),
    motivoRechazo: "No se presentó la lista de deportistas",
    usuarioId: "user-32",
    usuarioNombre: "Fernando Salinas",
  },
];
