import { Evento } from "../interfaces/evento";

export const eventos: Evento[] = [
  {
    codigoItem: 1,
    tipoParticipacion: "Individual",
    tipoEvento: "Competencia",
    evento: "Maratón Ciudad de Buenos Aires",
    sexo: "Mixto",
    deporte: "Atletismo",
    provincia: "Buenos Aires",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2023-10-15",
    fechaFin: "2023-10-15",
    categoria: "Adultos",
    numeroEntrenadoresHombres: 5,
    numeroEntrenadoresMujeres: 3,
    numeroAtletasHombres: 150,
    numeroAtletasMujeres: 100,
    estado: "solicitado",
  },
  {
    codigoItem: 2,
    tipoParticipacion: "Equipo",
    tipoEvento: "Torneo",
    evento: "Copa Nacional de Fútbol",
    sexo: "Masculino",
    deporte: "Fútbol",
    provincia: "Córdoba",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2023-11-01",
    fechaFin: "2023-11-15",
    categoria: "Juveniles",
    numeroEntrenadoresHombres: 10,
    numeroEntrenadoresMujeres: 2,
    numeroAtletasHombres: 200,
    numeroAtletasMujeres: 0,
    estado: "disponible",
  },
  {
    codigoItem: 3,
    tipoParticipacion: "Individual",
    tipoEvento: "Competencia",
    evento: "Triatlón Patagonia",
    sexo: "Mixto",
    deporte: "Triatlón",
    provincia: "Neuquén",
    pais: "Argentina",
    alcance: "Internacional",
    fechaInicio: "2023-12-05",
    fechaFin: "2023-12-07",
    categoria: "Adultos",
    numeroEntrenadoresHombres: 4,
    numeroEntrenadoresMujeres: 2,
    numeroAtletasHombres: 80,
    numeroAtletasMujeres: 60,
    estado: "rechazado",
    motivoRechazo:
      "El documento presentado no cumple con los requisitos mínimos. Por favor, revisa que incluya toda la información solicitada y vuelve a enviarlo.",
  },
  {
    codigoItem: 4,
    tipoParticipacion: "Equipo",
    tipoEvento: "Torneo",
    evento: "Liga Nacional de Vóley",
    sexo: "Femenino",
    deporte: "Vóley",
    provincia: "Santa Fe",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2023-09-10",
    fechaFin: "2023-09-20",
    categoria: "Juveniles",
    numeroEntrenadoresHombres: 3,
    numeroEntrenadoresMujeres: 5,
    numeroAtletasHombres: 0,
    numeroAtletasMujeres: 2,
    estado: "aceptado",
  },
  {
    codigoItem: 5,
    tipoParticipacion: "Individual",
    tipoEvento: "Competencia",
    evento: "Campeonato Nacional de Natación",
    sexo: "Mixto",
    deporte: "Natación",
    provincia: "Mendoza",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2023-08-15",
    fechaFin: "2023-08-18",
    categoria: "Infantiles",
    numeroEntrenadoresHombres: 6,
    numeroEntrenadoresMujeres: 4,
    numeroAtletasHombres: 60,
    numeroAtletasMujeres: 70,
    estado: "disponible",
  },
  {
    codigoItem: 6,
    tipoParticipacion: "Equipo",
    tipoEvento: "Torneo",
    evento: "Copa Federal de Hockey",
    sexo: "Femenino",
    deporte: "Hockey",
    provincia: "Buenos Aires",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2023-07-20",
    fechaFin: "2023-07-25",
    categoria: "Adultos",
    numeroEntrenadoresHombres: 2,
    numeroEntrenadoresMujeres: 6,
    numeroAtletasHombres: 0,
    numeroAtletasMujeres: 2,
    estado: "disponible",
  },
  {
    codigoItem: 7,
    tipoParticipacion: "Individual",
    tipoEvento: "Competencia",
    evento: "Open Internacional de Tenis",
    sexo: "Masculino",
    deporte: "Tenis",
    provincia: "Salta",
    pais: "Argentina",
    alcance: "Internacional",
    fechaInicio: "2023-06-10",
    fechaFin: "2023-06-15",
    categoria: "Adultos",
    numeroEntrenadoresHombres: 5,
    numeroEntrenadoresMujeres: 1,
    numeroAtletasHombres: 4,
    numeroAtletasMujeres: 0,
    estado: "disponible",
  },
  {
    codigoItem: 8,
    tipoParticipacion: "Equipo",
    tipoEvento: "Torneo",
    evento: "Campeonato Nacional de Básquet",
    sexo: "Masculino",
    deporte: "Básquet",
    provincia: "Chaco",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2023-05-05",
    fechaFin: "2023-05-12",
    categoria: "Juveniles",
    numeroEntrenadoresHombres: 8,
    numeroEntrenadoresMujeres: 2,
    numeroAtletasHombres: 5,
    numeroAtletasMujeres: 0,
    estado: "disponible",
  },
  {
    codigoItem: 9,
    tipoParticipacion: "Individual",
    tipoEvento: "Competencia",
    evento: "Campeonato Nacional de Judo",
    sexo: "Mixto",
    deporte: "Judo",
    provincia: "Tucumán",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2023-04-20",
    fechaFin: "2023-04-22",
    categoria: "Infantiles",
    numeroEntrenadoresHombres: 3,
    numeroEntrenadoresMujeres: 2,
    numeroAtletasHombres: 5,
    numeroAtletasMujeres: 0,
    estado: "disponible",
  },
  {
    codigoItem: 10,
    tipoParticipacion: "Equipo",
    tipoEvento: "Torneo",
    evento: "Copa Nacional de Rugby",
    sexo: "Masculino",
    deporte: "Rugby",
    provincia: "Entre Ríos",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2023-03-15",
    fechaFin: "2023-03-20",
    categoria: "Adultos",
    numeroEntrenadoresHombres: 7,
    numeroEntrenadoresMujeres: 1,
    numeroAtletasHombres: 5,
    numeroAtletasMujeres: 0,
    estado: "disponible",
  },
  {
    codigoItem: 11,
    tipoParticipacion: "Individual",
    tipoEvento: "Competencia",
    evento: "Campeonato Nacional de Gimnasia",
    sexo: "Femenino",
    deporte: "Gimnasia",
    provincia: "San Juan",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2023-02-10",
    fechaFin: "2023-02-12",
    categoria: "Juveniles",
    numeroEntrenadoresHombres: 2,
    numeroEntrenadoresMujeres: 5,
    numeroAtletasHombres: 0,
    numeroAtletasMujeres: 5,
    estado: "disponible",
  },
  {
    codigoItem: 12,
    tipoParticipacion: "Equipo",
    tipoEvento: "Torneo",
    evento: "Copa Nacional de Handball",
    sexo: "Mixto",
    deporte: "Handball",
    provincia: "Misiones",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2023-01-20",
    fechaFin: "2023-01-25",
    categoria: "Adultos",
    numeroEntrenadoresHombres: 4,
    numeroEntrenadoresMujeres: 3,
    numeroAtletasHombres: 5,
    numeroAtletasMujeres: 0,
    estado: "disponible",
  },
  {
    codigoItem: 13,
    tipoParticipacion: "Individual",
    tipoEvento: "Competencia",
    evento: "Campeonato Nacional de Esgrima",
    sexo: "Mixto",
    deporte: "Esgrima",
    provincia: "La Pampa",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2022-12-10",
    fechaFin: "2022-12-12",
    categoria: "Adultos",
    numeroEntrenadoresHombres: 2,
    numeroEntrenadoresMujeres: 2,
    numeroAtletasHombres: 0,
    numeroAtletasMujeres: 5,
    estado: "disponible",
  },
  {
    codigoItem: 14,
    tipoParticipacion: "Equipo",
    tipoEvento: "Torneo",
    evento: "Copa Nacional de Softbol",
    sexo: "Femenino",
    deporte: "Softbol",
    provincia: "Formosa",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2022-11-05",
    fechaFin: "2022-11-10",
    categoria: "Juveniles",
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 4,
    numeroAtletasHombres: 0,
    numeroAtletasMujeres: 5,
    estado: "disponible",
  },
  {
    codigoItem: 15,
    tipoParticipacion: "Individual",
    tipoEvento: "Competencia",
    evento: "Campeonato Nacional de Ciclismo",
    sexo: "Masculino",
    deporte: "Ciclismo",
    provincia: "San Luis",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2022-10-15",
    fechaFin: "2022-10-17",
    categoria: "Adultos",
    numeroEntrenadoresHombres: 3,
    numeroEntrenadoresMujeres: 1,
    numeroAtletasHombres: 5,
    numeroAtletasMujeres: 0,
    estado: "disponible",
  },
  {
    codigoItem: 16,
    tipoParticipacion: "Equipo",
    tipoEvento: "Torneo",
    evento: "Copa Nacional de Básquet Femenino",
    sexo: "Femenino",
    deporte: "Básquet",
    provincia: "Santa Cruz",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2022-09-10",
    fechaFin: "2022-09-15",
    categoria: "Juveniles",
    numeroEntrenadoresHombres: 2,
    numeroEntrenadoresMujeres: 3,
    numeroAtletasHombres: 0,
    numeroAtletasMujeres: 2,
    estado: "disponible",
  },
  {
    codigoItem: 17,
    tipoParticipacion: "Individual",
    tipoEvento: "Competencia",
    evento: "Campeonato Nacional de Boxeo",
    sexo: "Masculino",
    deporte: "Boxeo",
    provincia: "Corrientes",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2022-08-20",
    fechaFin: "2022-08-22",
    categoria: "Adultos",
    numeroEntrenadoresHombres: 4,
    numeroEntrenadoresMujeres: 0,
    numeroAtletasHombres: 2,
    numeroAtletasMujeres: 0,
    estado: "disponible",
  },
  {
    codigoItem: 18,
    tipoParticipacion: "Equipo",
    tipoEvento: "Torneo",
    evento: "Copa Nacional de Hockey Masculino",
    sexo: "Masculino",
    deporte: "Hockey",
    provincia: "Jujuy",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2022-07-10",
    fechaFin: "2022-07-15",
    categoria: "Juveniles",
    numeroEntrenadoresHombres: 3,
    numeroEntrenadoresMujeres: 1,
    numeroAtletasHombres: 5,
    numeroAtletasMujeres: 0,
    estado: "disponible",
  },
  {
    codigoItem: 19,
    tipoParticipacion: "Individual",
    tipoEvento: "Competencia",
    evento: "Campeonato Nacional de Taekwondo",
    sexo: "Mixto",
    deporte: "Taekwondo",
    provincia: "Río Negro",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2022-06-05",
    fechaFin: "2022-06-07",
    categoria: "Infantiles",
    numeroEntrenadoresHombres: 2,
    numeroEntrenadoresMujeres: 2,
    numeroAtletasHombres: 1,
    numeroAtletasMujeres: 2,
    estado: "disponible",
  },
  {
    codigoItem: 20,
    tipoParticipacion: "Equipo",
    tipoEvento: "Torneo",
    evento: "Copa Nacional de Futsal",
    sexo: "Masculino",
    deporte: "Futsal",
    provincia: "Catamarca",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2022-05-10",
    fechaFin: "2022-05-15",
    categoria: "Adultos",
    numeroEntrenadoresHombres: 5,
    numeroEntrenadoresMujeres: 0,
    numeroAtletasHombres: 7,
    numeroAtletasMujeres: 0,
    estado: "disponible",
  },
  {
    codigoItem: 21,
    tipoParticipacion: "Individual",
    tipoEvento: "Competencia",
    evento: "Campeonato Nacional de Patinaje",
    sexo: "Femenino",
    deporte: "Patinaje",
    provincia: "San Luis",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2022-04-20",
    fechaFin: "2022-04-22",
    categoria: "Juveniles",
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 3,
    numeroAtletasHombres: 0,
    numeroAtletasMujeres: 3,
    estado: "disponible",
  },
  {
    codigoItem: 22,
    tipoParticipacion: "Equipo",
    tipoEvento: "Torneo",
    evento: "Copa Nacional de Vóley Masculino",
    sexo: "Masculino",
    deporte: "Vóley",
    provincia: "Santa Fe",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2022-03-10",
    fechaFin: "2022-03-15",
    categoria: "Juveniles",
    numeroEntrenadoresHombres: 4,
    numeroEntrenadoresMujeres: 0,
    numeroAtletasHombres: 2,
    numeroAtletasMujeres: 0,
    estado: "disponible",
  },
  {
    codigoItem: 23,
    tipoParticipacion: "Individual",
    tipoEvento: "Competencia",
    evento: "Campeonato Nacional de Karate",
    sexo: "Mixto",
    deporte: "Karate",
    provincia: "Buenos Aires",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2022-02-05",
    fechaFin: "2022-02-07",
    categoria: "Infantiles",
    numeroEntrenadoresHombres: 2,
    numeroEntrenadoresMujeres: 1,
    numeroAtletasHombres: 2,
    numeroAtletasMujeres: 0,
    estado: "disponible",
  },
  {
    codigoItem: 24,
    tipoParticipacion: "Equipo",
    tipoEvento: "Torneo",
    evento: "Copa Nacional de Waterpolo",
    sexo: "Masculino",
    deporte: "Waterpolo",
    provincia: "Mendoza",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2022-01-15",
    fechaFin: "2022-01-20",
    categoria: "Adultos",
    numeroEntrenadoresHombres: 3,
    numeroEntrenadoresMujeres: 0,
    numeroAtletasHombres: 2,
    numeroAtletasMujeres: 0,
    estado: "disponible",
  },
  {
    codigoItem: 25,
    tipoParticipacion: "Individual",
    tipoEvento: "Competencia",
    evento: "Campeonato Nacional de Escalada",
    sexo: "Mixto",
    deporte: "Escalada",
    provincia: "Córdoba",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2021-12-10",
    fechaFin: "2021-12-12",
    categoria: "Juveniles",
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 1,
    numeroAtletasHombres: 2,
    numeroAtletasMujeres: 0,
    estado: "disponible",
  },
  {
    codigoItem: 26,
    tipoParticipacion: "Equipo",
    tipoEvento: "Torneo",
    evento: "Copa Nacional de Polo",
    sexo: "Masculino",
    deporte: "Polo",
    provincia: "Buenos Aires",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2021-11-05",
    fechaFin: "2021-11-10",
    categoria: "Adultos",
    numeroEntrenadoresHombres: 2,
    numeroEntrenadoresMujeres: 0,
    numeroAtletasHombres: 2,
    numeroAtletasMujeres: 0,
    estado: "disponible",
  },
  {
    codigoItem: 27,
    tipoParticipacion: "Individual",
    tipoEvento: "Competencia",
    evento: "Campeonato Nacional de Skate",
    sexo: "Mixto",
    deporte: "Skate",
    provincia: "Santa Cruz",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2021-10-15",
    fechaFin: "2021-10-17",
    categoria: "Juveniles",
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 1,
    numeroAtletasHombres: 2,
    numeroAtletasMujeres: 0,
    estado: "disponible",
  },
  {
    codigoItem: 28,
    tipoParticipacion: "Equipo",
    tipoEvento: "Torneo",
    evento: "Copa Nacional de Remo",
    sexo: "Mixto",
    deporte: "Remo",
    provincia: "Entre Ríos",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2021-09-10",
    fechaFin: "2021-09-15",
    categoria: "Adultos",
    numeroEntrenadoresHombres: 2,
    numeroEntrenadoresMujeres: 2,
    numeroAtletasHombres: 2,
    numeroAtletasMujeres: 0,
    estado: "disponible",
  },
  {
    codigoItem: 29,
    tipoParticipacion: "Individual",
    tipoEvento: "Competencia",
    evento: "Campeonato Nacional de Tiro",
    sexo: "Masculino",
    deporte: "Tiro",
    provincia: "Chubut",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2021-08-05",
    fechaFin: "2021-08-07",
    categoria: "Adultos",
    numeroEntrenadoresHombres: 2,
    numeroEntrenadoresMujeres: 0,
    numeroAtletasHombres: 2,
    numeroAtletasMujeres: 0,
    estado: "disponible",
  },
  {
    codigoItem: 30,
    tipoParticipacion: "Equipo",
    tipoEvento: "Torneo",
    evento: "Copa Nacional de Rugby Femenino",
    sexo: "Femenino",
    deporte: "Rugby",
    provincia: "Tucumán",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2021-07-10",
    fechaFin: "2021-07-15",
    categoria: "Juveniles",
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 2,
    numeroAtletasHombres: 2,
    numeroAtletasMujeres: 2,
    estado: "disponible",
  },
  {
    codigoItem: 31,
    tipoParticipacion: "Individual",
    tipoEvento: "Competencia",
    evento: "Campeonato Nacional de Pentatlón",
    sexo: "Mixto",
    deporte: "Pentatlón",
    provincia: "La Rioja",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2021-06-05",
    fechaFin: "2021-06-07",
    categoria: "Adultos",
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 1,
    numeroAtletasHombres: 2,
    numeroAtletasMujeres: 2,
    estado: "disponible",
  },
  {
    codigoItem: 32,
    tipoParticipacion: "Equipo",
    tipoEvento: "Torneo",
    evento: "Copa Nacional de Básquet Mixto",
    sexo: "Mixto",
    deporte: "Básquet",
    provincia: "Santa Fe",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2021-05-10",
    fechaFin: "2021-05-15",
    categoria: "Infantiles",
    numeroEntrenadoresHombres: 2,
    numeroEntrenadoresMujeres: 2,
    numeroAtletasHombres: 1,
    numeroAtletasMujeres: 1,
    estado: "disponible",
  },
  {
    codigoItem: 33,
    tipoParticipacion: "Individual",
    tipoEvento: "Competencia",
    evento: "Campeonato Nacional de Mountain Bike",
    sexo: "Masculino",
    deporte: "Mountain Bike",
    provincia: "San Juan",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2021-04-20",
    fechaFin: "2021-04-22",
    categoria: "Juveniles",
    numeroEntrenadoresHombres: 2,
    numeroEntrenadoresMujeres: 0,
    numeroAtletasHombres: 1,
    numeroAtletasMujeres: 0,
    estado: "disponible",
  },
  {
    codigoItem: 34,
    tipoParticipacion: "Equipo",
    tipoEvento: "Torneo",
    evento: "Copa Nacional de Hockey Mixto",
    sexo: "Mixto",
    deporte: "Hockey",
    provincia: "Buenos Aires",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2021-03-15",
    fechaFin: "2021-03-20",
    categoria: "Adultos",
    numeroEntrenadoresHombres: 2,
    numeroEntrenadoresMujeres: 2,
    numeroAtletasHombres: 2,
    numeroAtletasMujeres: 2,
    estado: "disponible",
  },
  {
    codigoItem: 35,
    tipoParticipacion: "Individual",
    tipoEvento: "Competencia",
    evento: "Campeonato Nacional de Natación Juvenil",
    sexo: "Mixto",
    deporte: "Natación",
    provincia: "Mendoza",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2021-02-10",
    fechaFin: "2021-02-12",
    categoria: "Juveniles",
    numeroEntrenadoresHombres: 2,
    numeroEntrenadoresMujeres: 2,
    numeroAtletasHombres: 3,
    numeroAtletasMujeres: 1,
    estado: "disponible",
  },
  {
    codigoItem: 36,
    tipoParticipacion: "Equipo",
    tipoEvento: "Torneo",
    evento: "Copa Nacional de Fútbol Femenino",
    sexo: "Femenino",
    deporte: "Fútbol",
    provincia: "Córdoba",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2021-01-20",
    fechaFin: "2021-01-25",
    categoria: "Adultos",
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 3,
    numeroAtletasHombres: 0,
    numeroAtletasMujeres: 2,
    estado: "disponible",
  },
  {
    codigoItem: 37,
    tipoParticipacion: "Individual",
    tipoEvento: "Competencia",
    evento: "Campeonato Nacional de Esquí",
    sexo: "Mixto",
    deporte: "Esquí",
    provincia: "Neuquén",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2020-12-10",
    fechaFin: "2020-12-12",
    categoria: "Juveniles",
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 1,
    numeroAtletasHombres: 1,
    numeroAtletasMujeres: 3,
    estado: "disponible",
  },
  {
    codigoItem: 38,
    tipoParticipacion: "Equipo",
    tipoEvento: "Torneo",
    evento: "Copa Nacional de Handball Masculino",
    sexo: "Masculino",
    deporte: "Handball",
    provincia: "Misiones",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2020-11-05",
    fechaFin: "2020-11-10",
    categoria: "Juveniles",
    numeroEntrenadoresHombres: 2,
    numeroEntrenadoresMujeres: 0,
    numeroAtletasHombres: 2,
    numeroAtletasMujeres: 0,
    estado: "disponible",
  },
  {
    codigoItem: 39,
    tipoParticipacion: "Individual",
    tipoEvento: "Competencia",
    evento: "Campeonato Nacional de Gimnasia Infantil",
    sexo: "Femenino",
    deporte: "Gimnasia",
    provincia: "San Juan",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2020-10-15",
    fechaFin: "2020-10-17",
    categoria: "Infantiles",
    numeroEntrenadoresHombres: 0,
    numeroEntrenadoresMujeres: 2,
    numeroAtletasHombres: 0,
    numeroAtletasMujeres: 4,
    estado: "disponible",
  },
  {
    codigoItem: 40,
    tipoParticipacion: "Equipo",
    tipoEvento: "Torneo",
    evento: "Copa Nacional de Softbol Masculino",
    sexo: "Masculino",
    deporte: "Softbol",
    provincia: "Formosa",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2020-09-10",
    fechaFin: "2020-09-15",
    categoria: "Juveniles",
    numeroEntrenadoresHombres: 2,
    numeroEntrenadoresMujeres: 0,
    numeroAtletasHombres: 4,
    numeroAtletasMujeres: 0,
    estado: "disponible",
  },
  {
    codigoItem: 41,
    tipoParticipacion: "Individual",
    tipoEvento: "Competencia",
    evento: "Campeonato Nacional de Ciclismo Infantil",
    sexo: "Masculino",
    deporte: "Ciclismo",
    provincia: "San Luis",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2020-08-20",
    fechaFin: "2020-08-22",
    categoria: "Infantiles",
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 0,
    numeroAtletasHombres: 2,
    numeroAtletasMujeres: 0,
    estado: "disponible",
  },
  {
    codigoItem: 42,
    tipoParticipacion: "Equipo",
    tipoEvento: "Torneo",
    evento: "Copa Nacional de Básquet Infantil",
    sexo: "Mixto",
    deporte: "Básquet",
    provincia: "Santa Cruz",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2020-07-10",
    fechaFin: "2020-07-15",
    categoria: "Infantiles",
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 1,
    numeroAtletasHombres: 2,
    numeroAtletasMujeres: 1,
    estado: "disponible",
  },
  {
    codigoItem: 43,
    tipoParticipacion: "Individual",
    tipoEvento: "Competencia",
    evento: "Campeonato Nacional de Boxeo Juvenil",
    sexo: "Masculino",
    deporte: "Boxeo",
    provincia: "Corrientes",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2020-06-05",
    fechaFin: "2020-06-07",
    categoria: "Juveniles",
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 0,
    numeroAtletasHombres: 2,
    numeroAtletasMujeres: 0,
    estado: "disponible",
  },
  {
    codigoItem: 44,
    tipoParticipacion: "Equipo",
    tipoEvento: "Torneo",
    evento: "Copa Nacional de Hockey Femenino Juvenil",
    sexo: "Femenino",
    deporte: "Hockey",
    provincia: "Jujuy",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2020-05-10",
    fechaFin: "2020-05-15",
    categoria: "Juveniles",
    numeroEntrenadoresHombres: 0,
    numeroEntrenadoresMujeres: 2,
    numeroAtletasHombres: 0,
    numeroAtletasMujeres: 1,
    estado: "disponible",
  },
  {
    codigoItem: 45,
    tipoParticipacion: "Individual",
    tipoEvento: "Competencia",
    evento: "Campeonato Nacional de Taekwondo Juvenil",
    sexo: "Mixto",
    deporte: "Taekwondo",
    provincia: "Río Negro",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2020-04-20",
    fechaFin: "2020-04-22",
    categoria: "Juveniles",
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 1,
    numeroAtletasHombres: 2,
    numeroAtletasMujeres: 1,
    estado: "disponible",
  },
  {
    codigoItem: 46,
    tipoParticipacion: "Equipo",
    tipoEvento: "Torneo",
    evento: "Copa Nacional de Futsal Juvenil",
    sexo: "Masculino",
    deporte: "Futsal",
    provincia: "Catamarca",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2020-03-10",
    fechaFin: "2020-03-15",
    categoria: "Juveniles",
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 0,
    numeroAtletasHombres: 2,
    numeroAtletasMujeres: 0,
    estado: "disponible",
  },
  {
    codigoItem: 47,
    tipoParticipacion: "Individual",
    tipoEvento: "Competencia",
    evento: "Campeonato Nacional de Patinaje Infantil",
    sexo: "Femenino",
    deporte: "Patinaje",
    provincia: "San Luis",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2020-02-05",
    fechaFin: "2020-02-07",
    categoria: "Infantiles",
    numeroEntrenadoresHombres: 0,
    numeroEntrenadoresMujeres: 1,
    numeroAtletasHombres: 0,
    numeroAtletasMujeres: 1,
    estado: "disponible",
  },
  {
    codigoItem: 48,
    tipoParticipacion: "Equipo",
    tipoEvento: "Torneo",
    evento: "Copa Nacional de Vóley Mixto Infantil",
    sexo: "Mixto",
    deporte: "Vóley",
    provincia: "Santa Fe",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2020-01-15",
    fechaFin: "2020-01-20",
    categoria: "Infantiles",
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 1,
    numeroAtletasHombres: 3,
    numeroAtletasMujeres: 2,
    estado: "disponible",
  },
  {
    codigoItem: 49,
    tipoParticipacion: "Individual",
    tipoEvento: "Competencia",
    evento: "Campeonato Nacional de Karate Infantil",
    sexo: "Mixto",
    deporte: "Karate",
    provincia: "Buenos Aires",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2019-12-10",
    fechaFin: "2019-12-12",
    categoria: "Infantiles",
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 1,
    numeroAtletasHombres: 2,
    numeroAtletasMujeres: 1,
    estado: "disponible",
  },
  {
    codigoItem: 50,
    tipoParticipacion: "Equipo",
    tipoEvento: "Torneo",
    evento: "Copa Nacional de Waterpolo Juvenil",
    sexo: "Masculino",
    deporte: "Waterpolo",
    provincia: "Mendoza",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2019-11-05",
    fechaFin: "2019-11-10",
    categoria: "Juveniles",
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 0,
    numeroAtletasHombres: 1,
    numeroAtletasMujeres: 0,
    estado: "disponible",
  },
  {
    codigoItem: 51,
    tipoParticipacion: "Individual",
    tipoEvento: "Competencia",
    evento: "Campeonato Nacional de Escalada Infantil",
    sexo: "Mixto",
    deporte: "Escalada",
    provincia: "Córdoba",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2019-10-15",
    fechaFin: "2019-10-17",
    categoria: "Infantiles",
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 0,
    numeroAtletasHombres: 2,
    numeroAtletasMujeres: 1,
    estado: "disponible",
  },
  {
    codigoItem: 52,
    tipoParticipacion: "Equipo",
    tipoEvento: "Torneo",
    evento: "Copa Nacional de Polo Juvenil",
    sexo: "Masculino",
    deporte: "Polo",
    provincia: "Buenos Aires",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2019-09-10",
    fechaFin: "2019-09-15",
    categoria: "Juveniles",
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 0,
    numeroAtletasHombres: 1,
    numeroAtletasMujeres: 0,
    estado: "disponible",
  },
  {
    codigoItem: 53,
    tipoParticipacion: "Individual",
    tipoEvento: "Competencia",
    evento: "Campeonato Nacional de Skate Infantil",
    sexo: "Mixto",
    deporte: "Skate",
    provincia: "Santa Cruz",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2019-08-05",
    fechaFin: "2019-08-07",
    categoria: "Infantiles",
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 0,
    numeroAtletasHombres: 2,
    numeroAtletasMujeres: 2,
    estado: "disponible",
  },
  {
    codigoItem: 54,
    tipoParticipacion: "Equipo",
    tipoEvento: "Torneo",
    evento: "Copa Nacional de Remo Infantil",
    sexo: "Mixto",
    deporte: "Remo",
    provincia: "Entre Ríos",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2019-07-10",
    fechaFin: "2019-07-15",
    categoria: "Infantiles",
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 1,
    numeroAtletasHombres: 3,
    numeroAtletasMujeres: 3,
    estado: "disponible",
  },
  {
    codigoItem: 55,
    tipoParticipacion: "Individual",
    tipoEvento: "Competencia",
    evento: "Campeonato Nacional de Tiro Juvenil",
    sexo: "Masculino",
    deporte: "Tiro",
    provincia: "Chubut",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2019-06-05",
    fechaFin: "2019-06-07",
    categoria: "Juveniles",
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 0,
    numeroAtletasHombres: 4,
    numeroAtletasMujeres: 0,
    estado: "disponible",
  },
  {
    codigoItem: 56,
    tipoParticipacion: "Equipo",
    tipoEvento: "Torneo",
    evento: "Copa Nacional de Rugby Mixto Infantil",
    sexo: "Mixto",
    deporte: "Rugby",
    provincia: "Tucumán",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2019-05-10",
    fechaFin: "2019-05-15",
    categoria: "Infantiles",
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 1,
    numeroAtletasHombres: 4,
    numeroAtletasMujeres: 4,
    estado: "disponible",
  },
  {
    codigoItem: 57,
    tipoParticipacion: "Individual",
    tipoEvento: "Competencia",
    evento: "Campeonato Nacional de Pentatlón Infantil",
    sexo: "Mixto",
    deporte: "Pentatlón",
    provincia: "La Rioja",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2019-04-20",
    fechaFin: "2019-04-22",
    categoria: "Infantiles",
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 0,
    numeroAtletasHombres: 2,
    numeroAtletasMujeres: 1,
    estado: "disponible",
  },
  {
    codigoItem: 58,
    tipoParticipacion: "Equipo",
    tipoEvento: "Torneo",
    evento: "Copa Nacional de Básquet Juvenil",
    sexo: "Masculino",
    deporte: "Básquet",
    provincia: "Santa Fe",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2019-03-10",
    fechaFin: "2019-03-15",
    categoria: "Juveniles",
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 0,
    numeroAtletasHombres: 2,

    numeroAtletasMujeres: 0,
    estado: "disponible",
  },
  {
    codigoItem: 59,
    tipoParticipacion: "Individual",
    tipoEvento: "Competencia",
    evento: "Campeonato Nacional de Mountain Bike Infantil",
    sexo: "Masculino",
    deporte: "Mountain Bike",
    provincia: "San Juan",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2019-02-05",
    fechaFin: "2019-02-07",
    categoria: "Infantiles",
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 0,
    numeroAtletasHombres: 2,
    numeroAtletasMujeres: 0,
    estado: "disponible",
  },
  {
    codigoItem: 60,
    tipoParticipacion: "Equipo",
    tipoEvento: "Torneo",
    evento: "Copa Nacional de Hockey Infantil",
    sexo: "Mixto",
    deporte: "Hockey",
    provincia: "Buenos Aires",
    pais: "Argentina",
    alcance: "Nacional",
    fechaInicio: "2019-01-15",
    fechaFin: "2019-01-20",
    categoria: "Infantiles",
    numeroEntrenadoresHombres: 1,
    numeroEntrenadoresMujeres: 1,
    numeroAtletasHombres: 3,
    numeroAtletasMujeres: 3,
    estado: "disponible",
  },
];
